myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student.urls')),
]

myapp/student/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('signup', views.userSignUp, name='signup'),
    path('login', views.userlogin, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('student/', views.student_page, name="student"),
    path('student_marks/', views.student_marks_page, name="student_marks"),
    path('studentInfoView/', views.studentInfoView_page, name="studentInfoView_page"),
    path('studentView/<int:rollNo>/', views.studentView_page, name="studentView"),
    path('search/', views.search_page, name="search"),
    path('editStudentInfo/<int:rollNo>/', views.EditStudentInfo, name="EditStudentInfo"),
    path('deleteStudentInfo/<int:rollNo>/', views.deleteStudentInfo, name="deleteStudentInfo"),
    path('geturl/', views.geturl_page, name='geturl'),

    
]   
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/student/models.py
from django.db import models

# Create your models here.

class StudentInfo(models.Model):
    rollNo = models.IntegerField(primary_key=True,  unique=True)
    name = models.CharField(max_length=255, null=False, blank=False )
    student_class = models.IntegerField(null=False, blank=False )
    school = models.CharField(max_length=255, null=False, blank=False)
    mobile = models.CharField(max_length=10, null=False, blank=False)
    address = models.CharField(max_length=255, null=True, blank=True)

class StudentAcademics(models.Model):
    rollNo = models.ForeignKey(StudentInfo, null=True, blank=True, on_delete=models.SET_NULL)
    maths = models.IntegerField( null=True, blank=True )
    physics = models.IntegerField( null=True, blank=True )
    chemistry = models.IntegerField( null=True, blank=True )
    biology = models.IntegerField( null=True, blank=True )
    english = models.IntegerField( null=True, blank=True )
    

myapp/student/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import *
# from django.contrib.auth.models import StudentInfo
from .models import StudentInfo
from .models import StudentAcademics


class SignUpForm(UserCreationForm):
    class Meta:
        fields = ('username','first_name','last_name','email','password1', 'password2')
        model = User

    def __init__(self,*args,**kwargs):
        super(SignUpForm, self).__init__(*args,**kwargs)
        self.fields['password2'].label = 'Confirm Password (again)'
        self.fields['email'].label = 'Email'
        self.fields['username']
        self.fields['first_name']
        self.fields['email']
        self.fields['password1']
        self.fields['password2']
class LoginForm(AuthenticationForm):
    class Meta:
        fields = ('username','password')
    def __init__(self,*args,**kwargs):
        super(LoginForm, self).__init__(*args,**kwargs)
        self.fields['username']
        self.fields['password']



class StudentsForm(forms.ModelForm):
    class Meta:
        model = StudentInfo
        # fields = ["rollNo", "name", "student_class", "school", "mobile", "address"]
        fields = "__all__"


class StudentsAcademicsForm(forms.ModelForm):
    class Meta:
        model = StudentAcademics
        # fields = "__all__"
        fields = ["rollNo" ,"maths", "physics", "chemistry", "biology","english"]
        

myapp/student/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from django.shortcuts import render, redirect
from .forms import *
import requests
from bs4 import BeautifulSoup
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
# Create your views here.


# def student_page(request):
#     return render(request, "student.html")


def homepage(request):
    
    return render(request, 'home.html')

def userSignUp(request):
    if request.method == "POST":
        fms = SignUpForm(request.POST)
        if fms.is_valid():
            fms.save()
            print("sucess")
            return redirect('/login')
    else:
        fms = SignUpForm()
    return render(request, 'signup.html', {'forms' : fms})

# User Login funtion
def userlogin(request):
	if request.method == "POST":
		fms = LoginForm(request=request, data=request.POST)
		if fms.is_valid():
			uname = fms.cleaned_data['username']
			upass = fms.cleaned_data['password']
			user = authenticate(username=uname, password=upass)
			if user is not None:
				login(request, user)
				return redirect('/studentInfoView/')
	else:
		fms = LoginForm()
	return render(request, 'userlogin.html', {'forms' : fms})


# User Logout function
def user_logout(request):
    logout(request)
    return redirect('/studentInfoView/')



def student_page(request):
    if request.method == "POST":
        form = StudentsForm( request.POST)
        print(request.POST,"@@@@@@@@")
        if form.is_valid():
            print(form,"this is form1")
            form.save()
            print("save form")
        else:
            print("something worng 1111111")

        
    form = StudentsForm()
    context = {
        'form': form 
    }

    return render(request, "student.html",context )



def student_marks_page(request):
    if request.method == 'POST':
        
        form = StudentsAcademicsForm(request.POST)
        if form.is_valid():
            form.save()
            print("suceesfully") 
        else:
            print("error")
    Academic_form = StudentsAcademicsForm()
    StudentInfo_list = StudentInfo.objects.all()
    context = {"Academic_form": Academic_form , "StudentInfo_list" :StudentInfo_list}
    return render(request, "AcademicDetails.html", context)


def studentInfoView_page(request):
    StudentInfo_list = StudentInfo.objects.all()
    print(StudentInfo_list, "Alll list")
    form = StudentsForm()
    context = {"StudentInfo_list": StudentInfo_list , 'form': form }
    return render(request, "StudentInfoView.html", context)

def studentView_page(request, rollNo):
    getStudent = StudentAcademics.objects.get(rollNo_id=rollNo)
 
    print( getStudent.maths, "!!!!!!!!!!!!!!!!")
    StudentAcademic_list = StudentAcademics.objects.all()
    context = {"StudentAcademic_list": StudentAcademic_list , "getStudent":getStudent}
    return render(request , "StudentAcademicView.html", context)



def search_page(request):
    if request.method == 'GET':  
        student_name =  request.GET.get('search')    
        print(student_name ,"###############")  
        try:
            stname = StudentInfo.objects.filter(name=student_name)
            print(stname ,"!!!!!!!!!!!!!!!!!!")
            return render(request,"StudentInfoView.html",{"stname":stname})
        except:
            print("wrong")
            return render(request,"StudentInfoView.html",{"stname":stname})
    else:
        print("nothing")
        return render(request,"StudentInfoView.html")



def EditStudentInfo(request, rollNo):
    if request.method == "POST":
        EditStudentInfo = StudentInfo.objects.get(rollNo=rollNo)
        print(EditStudentInfo,"$$$$$$$$$$")
        EditStudentInfo.name = request.POST['name']
        EditStudentInfo.student_class = request.POST['student_class']
        EditStudentInfo.school = request.POST['school']
        EditStudentInfo.mobile = request.POST['mobile']
        EditStudentInfo.address = request.POST['address']
        EditStudentInfo.save()
        print("StudentInfo edited---------------------")
    else:
        print("error!!!!!!!!!!!")

    return redirect("/studentInfoView/")

@csrf_exempt
def deleteStudentInfo(request, rollNo):
    if request.method == "DELETE":
        delete_Info =  StudentInfo.objects.get(rollNo=rollNo)
        delete_Info.delete()
        print("fffffffffffffffffffff")
    else:
        print("error @@@@@@@@@")
    return redirect("/studentInfoView/")


def geturl_page(request):
      
    # geturl =  request.GET.get('geturls')
    geturl ='https://www.geeksforgeeks.org/'
    # geturl =  request.GET.get('geturls')
    s = requests.get(geturl)
    print(s,"yyyyyyyyyyyyyyyyyyyyyyyyyyyy")
    
    findurl =BeautifulSoup(s.text, 'html.parser')
    print(findurl,"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    urls = [] 
    for link in findurl.find_all():
        data = link.get('href')
        if (data == None):
            print("error")
        else:
            urls.append(data)
            
        print(data,"0000000000000000000000000000000000")
    print(urls,"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    return render(request,"UrlPageView.html" , {"urls":urls})
        

myapp/templates/AcademicDetails.html
{% block content %}
{% load widget_tweaks %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
</head>
<body>
    <h1 style="width: 50%; margin-left: 24%; color: gray;">Student Academic Details</h1>  
      <div style="width: 50%; margin-left: 24%;">
      <form method="POST" action="" id="edit-holiday">
        {% csrf_token %}
        <div class="form-group">
            <label>Student Roll No</label>
            {% render_field Academic_form.rollNo value="" class="form-control" required=True %}
        </div>
        <div class="form-group">
            <label>Maths</label>
            {% render_field Academic_form.maths value=""  class="form-control" required=True %}
        </div>
        <div class="form-group">
            <label>Physics</label>
            {% render_field Academic_form.physics value=""  class="form-control" required=True %}
        </div>
        <div class="form-group">
            <label>Chemistry</label>
            {% render_field Academic_form.chemistry value="" class="form-control" required=True %}
        </div>
        <div class="form-group">
            <label>Biology</label>
            {% render_field Academic_form.biology value=""  class="form-control" required=True %}
        </div>
        <div class="form-group">
            <label>English</label>
            {% render_field Academic_form.english value=""  class="form-control" required=True %}
        </div>
        <div class="submit-section">
            <button class="btn btn-primary submit-btn" type="submit">Save</button>
        </div>
    </form>
    </div>
</body>
</html>
{% endblock %}

myapp/templates/StudentAcademicView.html
{% block content %}
{% load widget_tweaks %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<body>
  <div class="maindiv" style="width: 89%; margin-left: 6%;">


    <h1 style="width: 50%; margin-left: 24%; color: gray;">Student Academic Details</h1>
    <div>
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-striped custom-table mb-0">
                        <thead>
                            <tr>
                                <th>Roll No</th>
                                <th>Maths</th>
                                <th>Physics</th>
                                <th>Chemistry</th>
                                <th>Biology</th>
                                <th>English</th>

                            </tr>
                        </thead>
                        <tbody>

                            <td>{{ getStudent.rollNo_id }}</td>
                            <td> {{ getStudent.maths }}</td>
                            <td>{{ getStudent.physics }}</td>
                            <td>{{ getStudent.chemistry }}</td>
                            <td>{{ getStudent.biology }}</td>
                            <td>{{ getStudent.english }}</td>
                           

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


</div>
</body>

</html>
{% endblock %}

myapp/templates/StudentInfoView.html
{% block content %}
{% load static %}
{% load widget_tweaks %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    

    <style>
        .add-btn {
    background-color: #00c5fb;
    border: 1px solid #00c5fb;
    border-radius: 50px;
    color: #fff;
    float: right;
    margin-top: 3%;
    font-weight: 500;
    min-width: 140px;
}
.add-btn:hover,
.add-btn:focus,
.add-btn:active {
	background-color: #00b7ed;
	border: 1px solid #00b7ed;
    color: #fff;
}

.modal-btn .row {
	margin-left: -8px;
	margin-right: -8px;
}
.modal-btn  {
	padding-left: 8px;
	padding-right: 8px;
}
.continue-btn {
    background-color: #fff;
    border: 1px solid #00c5fb;
    border-radius: 50px;
    color: #00c5fb;
    width: 45%;
    float:left;
    font-size: 18px;
    font-weight: 600;
    padding: 10px 20px;
    text-align: center;
}
.continue-btn:hover,
.continue-btn:focus,
.continue-btn:active {
	background-color: #00c5fb;
	border: 1px solid #00c5fb;
	color: #fff;
}

.cancel-btn {
    background-color: #fff;
    border: 1px solid #00c5fb;
    border-radius: 50px;
    color: #00c5fb;
    /* display: block; */
    float:right;
    width: 45%;
    padding-top: 2%;
    font-size: 18px;
    font-weight: 600;
    padding: 10px 20px;
    text-align: center;
}
.cancel-btn:hover,
.cancel-btn:focus,
.cancel-btn:active {
	background-color: #00c5fb;
	border: 1px solid #00c5fb;
	color: #fff;
}

.loginbtn{
    margin-top: 3%;
    background-color: #00c5fb;
    border: 1px solid #00c5fb;
    color: #fff;
    width: 11%;
    border-radius: 18px;
    padding: 5px;
}



</style>

    
</head>
<body>
    <div class="maindiv" style="width: 89%; margin-left: 6%;">
    <div>
    <div><h1 style="width: 50%; float: left; color: gray;">Student Info Details</h1> </div>
  
    <div  style="float: right; margin-top: 3%; margin-left: 2%; " class="input-group">
        <form name="myform" method="GET" action="{% url 'search' %}" >  
        <input type="text" name="search" placeholder="Search by name" />
        </form> 
      </div>
       
    
    {% if request.user.is_authenticated  %}
    <div class="col-auto float-right ml-auto">
        <a href="/student/" class="btn add-btn" ><i class="fa fa-plus"></i> Add Students</a>
    </div>
     <button class="loginbtn"> <a style="color: #fff;" href="/logout/" class="logout mx-2"> Logout </a></button>
     
    {% else %}
    <button class="loginbtn"><a style="color: #fff;" href="/login" > Login </a></button>
  {% endif %}
  </div>
      <div >
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-striped custom-table mb-0">
                        <thead>
                            <tr>
                                <th>Roll No</th>
                                <th>Name </th>
                                <th>Student class</th>
                                <th>School Name</th>
                                <th>Mobile No</th>
                                <th>Address</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            {% if stname %}
                            {% for i in stname %}
                            <td>{{ i.rollNo }}</td> 
                                <td>{{ i.name}}</td>
                                <td>{{ i.student_class }}</td>
                                <td>{{i.school}}</td>
                                <td>{{ i.mobile }}</td>
                                <td>{{ i.address }}</td>   
                                {% endfor %}
                            {% endif %}

                            {% for i in StudentInfo_list %}
                                <tr>
                                <td>{{ i.rollNo }}</td>
                                {% if request.user.is_authenticated  %}   
                                <td><a href="{% url  'studentView' i.rollNo %}"> {{ i.name }}</a> </td>
                                {% else %}
                                <td> {{ i.name }}</td>
                                {% endif %}
                                <td>{{ i.student_class }}</td>
                                <td>{{ i.school }}</td>
                                <td>{{ i.mobile }}</td>
                                <td>{{ i.address }}</td>
                                <td class="text-right">
                            
                                    {% if request.user.is_authenticated  %}
                                    <a class="btn btn-info dropdown-item edit-Info" href="#" data-toggle="modal" data-target="#myModal" data-url="/editStudentInfo/{{i.rollNo}}/" data-name="{{i.name}}" data-student_class="{{i.student_class}}" data-school="{{i.school}}" data-mobile="{{i.mobile}}" data-address="{{i.address}}"><i class="fa fa-pencil m-r-5"></i> Edit</a>
                                    <a href="#" class="btn btn-warning  dropdown-item  deleteInfo" data-toggle="modal" data-target="#delete-info"   data-url="/deleteStudentInfo/{{i.rollNo}}/"><i class="fa fa-trash-o m-r-5"></i> Delete</a>
                                    {% endif %}
                                </td>
                                </tr>                                   
                            {% endfor %}

                          
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    			
        <!--  Edit  Modal -->
        <div class="modal fade" id="myModal" role="dialog" data-url="">
            <div class="modal-dialog">
            
              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Edit Student details</h4>
                </div>
                <div class="modal-body">
                    <form method="POST" action="" id="edit-Info">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>Full Name</label>
                            {% render_field form.name value=""  class="form-control"  %}
                        </div>
                        <div class="form-group">
                            <label>Class</label>
                            {% render_field form.student_class value="" class="form-control"  %}
                        </div>
                        <div class="form-group">
                            <label>Enter School Name</label>
                            {% render_field form.school value=""  class="form-control"  %}
                        </div>
                        <div class="form-group">
                            <label>Mobile No</label>
                            {% render_field form.mobile value=""  class="form-control"  %}
                        </div>
                        <div class="form-group">
                            <label>Address</label>
                            {% render_field form.address value=""  class="form-control"  %}
                        </div>
                        <div class="submit-section">
                            <button style="width: 16%;" class="btn btn-primary submit-btn" type="submit">Save</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>
              
            </div>
          </div>
          <!-- Edit info  -->

          <!-- delete Info -->
          <div class="modal custom-modal fade" id="delete-info" data-url="" data-val=""  role="dialog">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="form-header">
                            <h3>Delete Student</h3>
                            <p>Are you sure want to delete?</p>
                        </div>
                        <div class="modal-btn delete-action">
                            <div class="row">
                                <div class="col-2">
                                    <a href="/studentInfoView/" class="btn btn-primary continue-btn" id="student_delete_continue">Delete</a>
                                </div>
                                <div class="col-2">
                                    <a href="javascript:void(0);" data-dismiss="modal" class="btn btn-primary cancel-btn">Cancel</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

         <!-- delete Info -->
</div>


<script>
    $(document).ready(function () {
        $(".edit-Info").click(function () {
            var editItemUrl = $(this).data('url');
            var editItemname = $(this).data('name');
            var editItemstudent_class = $(this).data('student_class');
            var editItemschool = $(this).data('school');
            var editItemmobile = $(this).data('mobile');
            var editItemaddress = $(this).data('address');
            console.log(editItemUrl,"!!!!!!!!!!!!!!!")
            console.log(editItemname,"!!!!!!!!!!!!!!!")
            console.log(editItemstudent_class,"!!!!!!!!!!!!!!!")
            console.log(editItemschool,"!!!!!!!!!!!!!!!")
            console.log(editItemmobile,"!!!!!!!!!!!!!!!")
            console.log(editItemaddress,"!!!!!!!!!!!!!!!")

            $("#edit-Info").attr("action", editItemUrl);
            $("#edit-Info #id_name").val(editItemname);
            $("#edit-Info #id_student_class").val(editItemstudent_class);
            $("#edit-Info #id_school").val(editItemschool);
            $("#edit-Info #id_mobile").val(editItemmobile);
            $("#edit-Info #id_address").val(editItemaddress);
	});


    $(".deleteInfo").click(function () {
        // alert("sure")
		var url = $(this).data('url');
		$("#delete-info").data('url', url);
        console.log(url,"!!!!!!!!!!!!")
	});

	$("#student_delete_continue").click(function () {
        // alert("RRRRRRRRRRRRRRRRR")
		var url = $("#delete-info").data('url');
        console.log(url,"!!!!!!!!!!!!")
		$.ajax({
			url: url,
			type: "DELETE",
			contentType: false,
			processData: false,
			success: function (res) {
				location.reload();
			},
		});
	});


    });
</script>




</body>
</html>
{% endblock %}

myapp/templates/UrlPageView.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <h4>Search here </h4>
    <form name="myform" method="GET" action="{% url 'geturl' %}" >  
        <input class="form-group" type="text" value="" name="geturls" placeholder="Search " />
        <button class="btn btn-outline-success " type="submit">Search</button>
    </form> 
    <!-- <input type="text" name="geturls" /> -->
    {% for i in urls %}
    <p>{{i}}</p>
    {% endfor %}
</body>
</html>

myapp/templates/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <style>
    .btn-info {
    color: #fff;
    background-color: #02abe5;
    border-color: #46b8da;
}
    </style>
</head>
<body>
    <div class="maindiv" style="text-align: center;">
    <h3 >Welcome to home page</h3>
    <p>Click on button go to student info page </p>
    <button  class="btn btn-info"type="button"><a style="color:white" href="/studentInfoView/"> Student Info</a></button>
    </div>
</body>
</html>

myapp/templates/signup.html
{% load widget_tweaks %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <div class="container ">
        <!--Contact heading-->
        <h3 class=" m-0 text-center">Register here</h3>
        <div class="row ">
    
          <div class="col-md-6 offset-md-3">
            <form id="signup-form" method="POST" action="signup" role="form" novalidate>
                {% csrf_token %}
    
                  <div class="form-group">
                    <label for="username" class="font-weight-bold"> Username</label>
                    {% render_field forms.username value=""  class="form-control"  %}
                      <div class="help-block with-errors text-danger"></div>
                  </div>
                  <div class="form-group">
                    <label for="username" class="font-weight-bold"> First name</label>
                    {% render_field forms.first_name value=""  class="form-control"  %}
                      <div class="help-block with-errors text-danger"></div>
                  </div>
                  <div class="form-group">
                    <label for="username" class="font-weight-bold"> Email</label>
                    {% render_field forms.email value=""  class="form-control"  %}
                      <div class="help-block with-errors text-danger"></div>
                  </div>
                  <div class="form-group">
                    <label for="username" class="font-weight-bold"> Password1</label>
                    {% render_field forms.password1 value=""  class="form-control"  %}
                      <div class="help-block with-errors text-danger"></div>
                  </div>
                  <div class="form-group">
                    <label for="username" class="font-weight-bold"> Password2</label>
                    {% render_field forms.password2 value=""  class="form-control"  %}
                      <div class="help-block with-errors text-danger"></div>
                  </div>
                  
                  <div class="help-block with-errors text-danger">{{ forms.errors|striptags }}</div>
                  <div class="submit-section">
                    <button style="width: 16%;" class="btn btn-primary submit-btn" type="submit">Save</button>
                </div>
    
            </form>
    
            <!-- Login -->
            <p class="text-center m-3">Already member?
              <a href="{% url 'login' %}">Login</a>
            </p>
    
          </div>
    
        </div>
    
      </div>
</body>
</html>

myapp/templates/student.html
{% block content %}
{% load widget_tweaks %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
</head>
<body>
    <h1 style="width: 50%; margin-left: 24%; color: gray;" >Student Details </h1>  

  
      <div style="width: 50%; margin-left: 24%;">
        <form method="POST" action="" id="">
          {% csrf_token %}
          <div class="form-group">
              <label>Enter Roll No</label>
              {% render_field form.rollNo value="" type="number" class="form-control"  %}
          </div>
          <div class="form-group">
              <label>Full Name</label>
              {% render_field form.name value="" type="text" class="form-control"  %}
          </div>
          <div class="form-group">
              <label>Class</label>
              {% render_field form.student_class value="" type="number" class="form-control"  %}
          </div>
          <div class="form-group">
              <label>Enter School Name</label>
              {% render_field form.school value="" type="text" class="form-control"  %}
          </div>
          <div class="form-group">
              <label>Mobile No</label>
              {% render_field form.mobile value="" type="text" class="form-control"  %}
          </div>
          <div class="form-group">
              <label>Address</label>
              {% render_field form.address value="" type="text" class="form-control"  %}
          </div>
          <div class="submit-section">
              <button style="width: 16%;" class="btn btn-primary submit-btn" type="submit">Save</button>
          </div>
          <div  class="submit-section">
            <button style="width: 16%; float:right; margin-top: -5%;" class="btn btn-primary submit-btn"><a style="color: white;" href="/student_marks/"> Next </a></button>
        </div>
          
      </form>
      </div>
</body>
</html>
{% endblock %}